import Link from "next/link";
import { db } from "@/lib/db";

export default async function StudentsPage({ searchParams }: { searchParams: Promise<{ error?: string; created?: string }> }) {
  const { error, created } = await searchParams;
  const [students, departments, sections] = await Promise.all([
    db.studentProfile.findMany({ include: { user: true, department: true, section: true }, orderBy: { fullName: "asc" } }),
    db.department.findMany({ where: { active: true }, orderBy: { name: "asc" } }),
    db.section.findMany({ orderBy: [{ departmentId: "asc" }, { name: "asc" }] }),
  ]);
  return <>
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Link href="/admin/dashboard" className="text-sm font-semibold text-[#1e6fd9]">← Dashboard</Link><h1 className="mt-3 font-display text-4xl font-bold text-[#10233f]">Students</h1><p className="mt-2 text-slate-500">Create and manage college-issued accounts.</p></div><span className="rounded-full bg-blue-50 px-4 py-2 text-sm font-semibold text-[#1e6fd9]">{students.length} records</span></div>
    {created && <p className="mt-6 rounded-lg bg-emerald-50 px-4 py-3 text-sm text-emerald-700">Student account created. They must change the temporary password on first login.</p>}
    {error && <p className="mt-6 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}
    <div className="mt-8 grid gap-8 lg:grid-cols-[360px_1fr]">
      <form action="/api/admin/students" method="post" className="rounded-xl border border-slate-200 bg-white p-6"><h2 className="font-display text-xl font-bold text-[#10233f]">Add student</h2><div className="mt-5 space-y-4"><label className="block text-sm font-semibold text-slate-700">Full name<input name="fullName" required className="mt-1.5 w-full rounded-lg border border-slate-200 px-3 py-2.5" /></label><label className="block text-sm font-semibold text-slate-700">Register number<input name="registerNumber" required className="mt-1.5 w-full rounded-lg border border-slate-200 px-3 py-2.5" /></label><label className="block text-sm font-semibold text-slate-700">Email<input name="email" type="email" required className="mt-1.5 w-full rounded-lg border border-slate-200 px-3 py-2.5" /></label><label className="block text-sm font-semibold text-slate-700">Department<select name="departmentId" required className="mt-1.5 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5">{departments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="block text-sm font-semibold text-slate-700">Section<select name="sectionId" required className="mt-1.5 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5">{sections.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="block text-sm font-semibold text-slate-700">Year<input name="year" type="number" min="1" max="8" defaultValue="1" required className="mt-1.5 w-full rounded-lg border border-slate-200 px-3 py-2.5" /></label><label className="block text-sm font-semibold text-slate-700">Temporary password<input name="temporaryPassword" type="password" minLength={8} required className="mt-1.5 w-full rounded-lg border border-slate-200 px-3 py-2.5" /></label><button className="w-full rounded-lg bg-[#1e6fd9] py-3 font-bold text-white">Create account</button></div></form>
      <div className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-200 px-6 py-5"><h2 className="font-display text-xl font-bold text-[#10233f]">Student directory</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-4">Student</th><th className="px-6 py-4">Register number</th><th className="px-6 py-4">Department</th><th className="px-6 py-4">Year / section</th><th className="px-6 py-4">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{students.map((student) => <tr key={student.id}><td className="px-6 py-4"><p className="font-semibold text-[#10233f]">{student.fullName}</p><p className="text-xs text-slate-500">{student.user.email}</p></td><td className="px-6 py-4 text-slate-600">{student.registerNumber}</td><td className="px-6 py-4 text-slate-600">{student.department.name}</td><td className="px-6 py-4 text-slate-600">{student.year} · {student.section.name}</td><td className="px-6 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${student.user.status === "ACTIVE" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{student.user.status.toLowerCase()}</span></td></tr>)}</tbody></table>{students.length === 0 && <p className="p-10 text-center text-sm text-slate-500">No students yet. Add the first college-issued account.</p>}</div></div>
    </div>
  </>;
}