import "dotenv/config";
import { expect as baseExpect, type Page } from "@playwright/test";
import { PrismaClient, Prisma } from "@prisma/client";
import bcrypt from "bcryptjs";
import { randomUUID } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { pathToFileURL } from "node:url";
import { securityChecks } from "./e2e-security";
import { launchSecurityBrowser } from "./e2e-browser";
import { catalogueChecks } from "./e2e-catalog";
const expect = baseExpect.configure({ timeout: 20000 });

export async function runWorkflow(mode: "workflow" | "security" | "catalogue" = "workflow") {
    const db = new PrismaClient();
    const base = process.env.E2E_BASE_URL || "http://localhost:3000";
    const tag = "E2E-" + Date.now();
    const password = "Test-" + randomUUID();
    const newPassword = "Changed-" + randomUUID();
    const report: string[] = [];
    const checks = (message: string) => { report.push(message); console.log("PASS " + message); };
    const originalSettings = await db.adminSetting.findMany();
    const levels = await db.skillLevel.findMany({ orderBy: { order: "asc" } });
    if (!levels.length) throw new Error("Configure at least one skill level before testing");
    const beginnerLevel = levels.find(l => l.name === "Beginner") || levels[0];
    await mkdir("test-results", { recursive: true });
    await writeFile(`test-results/${tag}-settings-backup.json`, JSON.stringify({ tag, originalSettings, levels }, null, 2));
    const admin = await db.user.create({ data: { email: tag.toLowerCase() + "-admin@example.test", passwordHash: await bcrypt.hash(password, 12), role: "ADMIN" } });
    const department = await db.department.create({ data: { name: tag } });
    const section = await db.section.create({ data: { name: "TEST", departmentId: department.id } });
    const category = await db.skillCategory.create({ data: { name: tag, slug: tag.toLowerCase() } });
    const provider = await db.provider.create({ data: { name: tag, website: "https://developer.mozilla.org" } });
    const skill = await db.skill.create({ data: { name: tag + " Skill", slug: tag.toLowerCase(), categoryId: category.id, levelId: beginnerLevel.id } });
    const course = await db.course.create({ data: { name: tag + " Official Course", officialUrl: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide", officialUrlStatus: "VERIFIED", skillId: skill.id, providerId: provider.id, levelId: beginnerLevel.id, certificateAvailable: true } });
    await db.question.createMany({ data: Array.from({ length: 5 }, (_, i) => ({ skillId: skill.id, levelId: beginnerLevel.id, type: "SINGLE_CHOICE" as const, difficulty: "EASY" as const, prompt: tag + " test question " + i, options: ["Correct", "Incorrect"], correctAnswer: "Correct" })) });
    const { browser, close: closeBrowser } = await launchSecurityBrowser();
    const adminContext = await browser.newContext({ baseURL: base });
    const studentContext = browser.contexts()[0];
    const adminPage = await adminContext.newPage();
    const studentPage = studentContext.pages()[0];
    const pageErrors: string[] = [];
    for (const page of [adminPage, studentPage]) page.on("pageerror", error => pageErrors.push(error.message));
    async function login(page: Page, role: string, identifier: string, secret: string) {
        await page.goto(base + "/" + role + "/login");
        await page.locator('[name="identifier"]').fill(identifier);
        await page.locator('[name="password"]').fill(secret);
        await page.locator(`form[action="/api/auth/${role}/login"] button[type="submit"]`).click();
        await page.waitForURL(/dashboard|password/, { timeout: 30000 });
    }
    async function jsonPost(path: string, data: object) { return studentContext.request.post(base + path, { data, maxRedirects: 0 }); }
    let studentId = "";
    let completed = false;
    try {
        await login(adminPage, "admin", admin.email, password); checks("Admin login");
        await adminPage.goto(base + "/admin/settings");
        await adminPage.locator('[name="assessmentQuestionCount"]').fill("2");
        await adminPage.locator('[name="assessmentDurationMinutes"]').fill("3");
        await adminPage.locator('[name="assessmentViolationLimit"]').fill("20");
        await adminPage.locator('[name="assessmentCooldownHours"]').fill("0.005");
        for (const level of levels) await adminPage.locator('[name="passMarks.' + level.name + '"]').fill("1");
        await adminPage.locator('[name="autoSubmitOnViolation"]').check();
        await adminPage.getByRole("button", { name: "Save System Settings" }).click();
        await adminPage.waitForURL(/saved=1/);
        expect((await db.adminSetting.findUniqueOrThrow({ where: { key: "assessmentQuestionCount" } })).value).toBe(2);
        checks("Admin settings persisted");
        await adminPage.goto(base + "/admin/students");
        await adminPage.waitForSelector('[name="fullName"]');
        const details = { fullName: tag + " Student", registerNumber: tag, email: tag.toLowerCase() + "@example.test", year: "2", temporaryPassword: password, confirmPassword: password };
        for (const [name, value] of Object.entries(details)) await adminPage.locator('[name="' + name + '"]').fill(value);
        await adminPage.locator('[name="departmentId"]').selectOption(department.id);
        await adminPage.locator('[name="sectionId"]').selectOption(section.id);
        await adminPage.getByRole("button", { name: /Add Student|Create Student/i }).click();
        await adminPage.waitForURL(/created=1/);
        const student = await db.studentProfile.findUniqueOrThrow({ where: { registerNumber: tag } });
        studentId = student.id;
        checks("Admin creates student");
        await login(studentPage, "student", tag, password);
        expect(studentPage.url()).toContain("/student/password");
        expect((await jsonPost("/api/student/assessment/start", { skillId: skill.id })).status()).toBe(403);
        await studentPage.locator('[name="password"]').fill(newPassword);
        await studentPage.getByRole("button", { name: "Continue to Student Dashboard" }).click();
        await studentPage.waitForURL(/student\/dashboard/);
        checks("Student login and forced password change; API bypass blocked");
        if (mode === "catalogue") {
            await catalogueChecks(db, adminPage, studentPage, { skillId: skill.id, courseId: course.id, providerId: provider.id, studentId, tag }, checks);
            completed = true;
            return;
        }
        if (mode === "security") {
            await securityChecks(db, adminContext, studentContext, { skillId: skill.id, departmentId: department.id, sectionId: section.id, tag }, checks);
            completed = true;
            return;
        }
        expect([403, 409]).toContain((await jsonPost("/api/student/assessment/start", { skillId: skill.id })).status());
        expect([403, 409]).toContain((await jsonPost("/api/student/learning", { skillId: skill.id, action: "complete" })).status());
        expect([403, 409]).toContain((await jsonPost("/api/student/certificates", { skillId: skill.id, credentialId: "UNAUTHORIZED", issuedAt: "2026-01-01" })).status());
        checks("Learning and certificate prerequisites enforced through API");
        await studentPage.goto(base + "/student/skills/" + skill.slug);
        await studentPage.waitForSelector('button:has-text("Learn Officially")', { timeout: 30000 });
        const popupPromise = studentPage.waitForEvent("popup", { timeout: 45000 }).catch(async () => {
            const pages = studentPage.context().pages();
            return pages.length > 1 ? pages[pages.length - 1] : null;
        });
        await studentPage.getByRole("button", { name: "Learn Officially" }).click();
        const official = await popupPromise;
        if (official) {
            expect(official.url()).toContain("developer.mozilla.org");
            await official.close().catch(() => undefined);
        }
        const selected = await db.studentSkill.findUniqueOrThrow({ where: { studentId_skillId: { studentId, skillId: skill.id } }, include: { selectedCourse: true } });
        expect(selected.selectedCourseId).toBe(course.id);
        expect(selected.selectedCourse?.providerId).toBe(provider.id);
        expect((await jsonPost("/api/student/assessment/start", { skillId: skill.id })).status()).toBe(409);
        expect((await jsonPost("/api/student/learning", { skillId: skill.id, action: "complete", completedAt: "2020-01-01" })).status()).toBe(400);
        await studentPage.goto(base + "/student/skills?q=" + encodeURIComponent(tag));
        await studentPage.getByRole("button", { name: "I Completed Learning" }).click();
        await studentPage.waitForURL(/student\/skills/);
        expect(await db.certificate.count({ where: { studentId } })).toBe(0);
        checks("Official course opens; learning completion does not unlock certificate");
        const start = studentPage.getByRole("button", { name: "Start Assessment" });
        await start.click();
        await studentPage.waitForURL(/student\/assessment\//);
        const attemptId = studentPage.url().split("/").pop()!;
        await studentPage.getByRole("button", { name: "Enter Secure Assessment Environment" }).click();
        await expect(studentPage.getByRole("button", { name: "Submit Assessment", exact: true })).toBeVisible();
        const clientId = await studentPage.evaluate(id => sessionStorage.getItem("skillcert_tab_" + id)!, attemptId);
        const first = await db.assessmentAttempt.findUniqueOrThrow({ where: { id: attemptId }, include: { answers: true } });
        expect(first.questionCount).toBe(2); expect(first.answers).toHaveLength(2);
        expect(first.expiresAt.getTime() - first.startedAt.getTime()).toBe(180000);
        expect(first.passMark).toBe(1); expect(first.violationLimit).toBe(20); expect(first.cooldownHours).toBe(0.005);
        expect(await studentPage.evaluate(() => !!document.fullscreenElement)).toBe(true);
        const payload = await (await jsonPost("/api/student/assessment/" + attemptId + "/heartbeat", { clientId })).json();
        expect(JSON.stringify(payload)).not.toMatch(/correctAnswer|explanation|passwordHash|questionSnapshot/);
        expect((await studentContext.request.get(base + "/student/results/" + attemptId, { maxRedirects: 0 })).status()).toBe(307);
        const outsider = await db.question.findFirstOrThrow({ where: { skillId: skill.id, id: { notIn: first.answers.map(a => a.questionId) } } });
        expect((await jsonPost("/api/student/assessment/" + attemptId + "/save", { clientId, responses: { [outsider.id]: "Correct" } })).status()).toBe(400);
        expect((await jsonPost("/api/student/assessment/" + attemptId + "/submit", { clientId, responses: { [outsider.id]: "Correct" } })).status()).toBe(400);
        expect((await jsonPost("/api/student/assessment/" + attemptId + "/submit", { clientId, score: 999, passed: true })).status()).toBe(400);
        expect((await jsonPost("/api/student/assessment/" + attemptId + "/claim", { clientId: randomUUID() })).status()).toBe(409);
        const concurrent = await Promise.all([jsonPost("/api/student/assessment/start", { skillId: skill.id }), jsonPost("/api/student/assessment/start", { skillId: skill.id })]);
        expect(concurrent.every(r => r.headers().location?.endsWith(attemptId))).toBe(true);
        expect(await db.assessmentAttempt.count({ where: { studentId, submittedAt: null } })).toBe(1);
        checks("Fullscreen, answer secrecy, result gating, question injection, score tampering and concurrent tab/start defenses");
        await studentPage.getByText("Incorrect", { exact: true }).click();
        await expect(studentPage.getByRole("status")).toContainText("Answer saved");
        const timerBefore = await studentPage.getByRole("timer").textContent();
        await studentPage.reload();
        await studentPage.getByRole("button", { name: "Enter Secure Assessment Environment" }).click();
        await expect(studentPage.getByRole("button", { name: "Submit Assessment", exact: true })).toBeVisible();
        const refreshed = await db.assessmentAttempt.findUniqueOrThrow({ where: { id: attemptId } });
        expect(refreshed.expiresAt.getTime()).toBe(first.expiresAt.getTime());
        await expect(studentPage.getByLabel("Incorrect", { exact: true })).toBeChecked();
        expect(await studentPage.getByRole("timer").textContent()).not.toBe("0:00");
        checks("Server timer and saved answers survive refresh (" + timerBefore + ")");
        const devtools = await studentContext.newCDPSession(studentPage);
        await devtools.send("Emulation.setFocusEmulationEnabled", { enabled: false });
        await studentPage.bringToFront();
        await expect.poll(() => studentPage.evaluate(() => document.visibilityState)).toBe("visible");
        const duplicate = await studentContext.newPage();
        await duplicate.bringToFront();
        await expect.poll(() => studentPage.evaluate(() => document.visibilityState)).toBe("hidden");
        await duplicate.goto(base + "/student/assessment/" + attemptId);
        await expect(duplicate.getByRole("status")).toContainText("already open in another tab");
        await expect.poll(async () => {
            const violations = await db.assessmentViolation.findMany({ where: { attemptId } });
            return ["TAB_SWITCH", "PAGE_HIDDEN", "WINDOW_BLUR"].every(type => violations.some(v => v.type === type));
        }).toBe(true);
        await studentPage.bringToFront();
        await duplicate.close();
        checks("Actual browser tab switch, page hidden and blur logged; duplicate tab blocked");
        if (await studentPage.evaluate(() => !!document.fullscreenElement)) await studentPage.evaluate(() => document.exitFullscreen());
        await expect(studentPage.getByRole("button", { name: "Enter Secure Assessment Environment" })).toBeVisible();
        await expect.poll(() => db.assessmentViolation.count({ where: { attemptId, type: "FULLSCREEN_EXIT" } })).toBeGreaterThan(0);
        await studentPage.getByRole("button", { name: "Enter Secure Assessment Environment" }).click();
        await studentPage.getByRole("button", { name: "Submit Assessment", exact: true }).click();
        await Promise.all([studentPage.waitForURL(/student\/results\//), studentPage.getByRole("button", { name: "Confirm Submit", exact: true }).click()]);
        const failed = await db.assessmentAttempt.findUniqueOrThrow({ where: { id: attemptId } });
        console.log("Cooldown evidence", JSON.stringify({ reason: failed.submissionReason, submittedAt: failed.submittedAt, reexamAvailableAt: failed.reexamAvailableAt, checkedAt: new Date() }));
        expect(failed.passed).toBe(false);
        expect(failed.submissionReason).toBe("MANUAL");
        expect(failed.reexamAvailableAt!.getTime() - failed.submittedAt!.getTime()).toBe(18000);
        expect((await jsonPost("/api/student/assessment/start", { skillId: skill.id })).status()).toBe(429);
        const frozenAnswers = await db.assessmentAnswer.findMany({ where: { attemptId }, orderBy: { position: "asc" } });
        const finalizationCount = await db.activityLog.count({ where: { studentId, action: "ASSESSMENT_FAILED" } });
        const retrySubmit = await jsonPost("/api/student/assessment/" + attemptId + "/submit", { clientId, responses: Object.fromEntries(first.answers.map(a => [a.questionId, "Correct"])) });
        expect(retrySubmit.ok()).toBe(true);
        expect((await db.assessmentAttempt.findUniqueOrThrow({ where: { id: attemptId } })).score).toBe(failed.score);
        await jsonPost("/api/student/assessment/" + attemptId + "/save", { clientId, responses: Object.fromEntries(first.answers.map(a => [a.questionId, "Correct"])) });
        expect(await db.assessmentAnswer.findMany({ where: { attemptId }, orderBy: { position: "asc" } })).toEqual(frozenAnswers);
        expect(await db.activityLog.count({ where: { studentId, action: "ASSESSMENT_FAILED" } })).toBe(finalizationCount);
        expect(await db.assessmentAttempt.findUniqueOrThrow({ where: { id: attemptId } })).toEqual(failed);
        checks("Timestamped fullscreen violation, failed result, cooldown and immutable duplicate submission");
        await new Promise(resolve => setTimeout(resolve, Math.max(0, failed.reexamAvailableAt!.getTime() - Date.now()) + 100));
        await studentPage.goto(base + "/student/skills?q=" + encodeURIComponent(tag));
        await studentPage.getByRole("button", { name: "Start Assessment" }).click();
        await studentPage.waitForURL(/student\/assessment\//);
        const secondId = studentPage.url().split("/").pop()!;
        const second = await db.assessmentAttempt.findUniqueOrThrow({ where: { id: secondId }, include: { answers: true } });
        expect(second.attemptNumber).toBe(2);
        expect(second.answers.some(a => !first.answers.some(b => a.questionId === b.questionId))).toBe(true);
        await studentPage.getByRole("button", { name: "Enter Secure Assessment Environment" }).click();
        await expect(studentPage.getByRole("button", { name: "Submit Assessment", exact: true })).toBeVisible();
        await studentPage.getByLabel("Correct", { exact: true }).check();
        await expect(studentPage.getByRole("status")).toContainText("Answer saved");
        await studentPage.getByRole("button", { name: "Submit Assessment", exact: true }).click();
        await Promise.all([studentPage.waitForURL(/student\/results\//), studentPage.getByRole("button", { name: "Confirm Submit", exact: true }).click()]);
        expect((await db.assessmentAttempt.findUniqueOrThrow({ where: { id: secondId } })).passed).toBe(true);
        expect((await db.certificate.findUniqueOrThrow({ where: { studentId_skillId: { studentId, skillId: skill.id } } })).status).toBe("UNLOCKED");
        checks("Real cooldown elapses, new randomized re-exam, pass and certificate unlock");
        await studentPage.goto(base + "/student/certificates");
        await studentPage.locator('[name="skillId"]').selectOption(skill.id);
        await studentPage.locator('[name="officialUrl"]').fill("https://example.test/credentials/" + tag);
        await studentPage.locator('[name="credentialId"]').fill(tag + "-CREDENTIAL");
        await studentPage.locator('[name="issuedAt"]').fill("2026-01-01");
        await Promise.all([studentPage.waitForResponse(response => response.url().endsWith("/api/student/certificates") && response.request().method() === "POST"), studentPage.getByRole("button", { name: "Submit Certificate for Verification" }).click()]);
        await studentPage.waitForURL(/success=1/);
        const certificate = await db.certificate.findUniqueOrThrow({ where: { studentId_skillId: { studentId, skillId: skill.id } } });
        expect(certificate.status).toBe("PENDING_VERIFICATION");
        await adminPage.goto(base + "/admin/certificates");
        const card = adminPage.locator('form[action="/api/admin/certificates"]').filter({ has: adminPage.locator(`[name="certificateId"][value="${certificate.id}"]`) });
        await card.locator('[name="remarks"]').fill("Please provide the issuer credential identifier.");
        await card.getByRole("button", { name: "Request Resubmission", exact: true }).click();
        await adminPage.waitForURL(/success=1/);
        expect((await db.certificate.findUniqueOrThrow({ where: { id: certificate.id } })).verifiedAt).toBeNull();
        await studentPage.reload();
        await studentPage.locator('[name="officialUrl"]').fill("https://example.test/credentials/" + tag);
        await studentPage.locator('[name="credentialId"]').fill(tag + "-ID-ONLY");
        await studentPage.locator('[name="issuedAt"]').fill("2026-01-01");
        await Promise.all([studentPage.waitForResponse(response => response.url().endsWith("/api/student/certificates") && response.request().method() === "POST"), studentPage.getByRole("button", { name: "Submit Certificate for Verification" }).click()]);
        await studentPage.waitForURL(/success=1/);
        await adminPage.reload();
        await card.locator('[name="remarks"]').fill("Issuer evidence needs correction.");
        await card.getByRole("button", { name: "Reject Credential", exact: true }).click();
        await adminPage.waitForURL(/success=1/);
        expect((await db.certificate.findUniqueOrThrow({ where: { id: certificate.id } })).status).toBe("REJECTED");
        expect((await jsonPost("/api/student/certificates", { skillId: skill.id, officialUrl: "https://example.test/credentials/" + tag, credentialId: tag + "-FINAL", issuedAt: "2026-01-01" })).status()).toBe(303);
        await adminPage.reload();
        checks("Request resubmission, rejection, and resubmission with URL+ID preserve review history");
        await card.locator('[name="remarks"]').fill("Credential checked against issuer record.");
        await card.getByRole("button", { name: "Approve & Unlock", exact: true }).click();
        await adminPage.waitForURL(/success=1/);
        await studentPage.reload();
        await expect(studentPage.getByText("VERIFIED", { exact: false })).toBeVisible();
        const verified = await db.studentSkill.findUniqueOrThrow({ where: { studentId_skillId: { studentId, skillId: skill.id } } });
        expect(verified.state).toBe("VERIFIED"); expect(verified.verifiedAt).not.toBeNull();
        const attributedCertificate = await db.certificate.findUniqueOrThrow({ where: { studentId_skillId: { studentId, skillId: skill.id } } });
        expect(attributedCertificate.courseId).toBe(course.id);
        expect(attributedCertificate.providerId).toBe(provider.id);
        await studentPage.screenshot({ path: "test-results/student-verified.png", fullPage: true });
        checks("Certificate submission, admin remarks/approval and immediate student Verified status");
        await studentPage.goto(base + "/student/dashboard");
        const dashboardCounts = { "Skills Started": 1, "Assessments Passed": 1, "Re-exams Pending": 0, "Certificates Verified": 1 };
        for (const [label, count] of Object.entries(dashboardCounts)) await expect(studentPage.getByText(label, { exact: true }).locator("..").locator("..").locator("p.text-3xl")).toHaveText(String(count));
        // The redesigned dashboard displays four KPIs; retain all prior data assertions.
        expect(await db.studentSkill.count({ where: { studentId, completedAt: null } })).toBe(0);
        expect(await db.assessmentAttempt.count({ where: { studentId } })).toBe(2);
        expect(await db.assessmentAttempt.count({ where: { studentId, passed: false } })).toBe(1);
        expect(await db.certificate.count({ where: { studentId, submittedAt: { not: null } } })).toBe(1);
        expect(await db.certificate.count({ where: { studentId, status: "PENDING_VERIFICATION" } })).toBe(0);
        await adminPage.goto(base + "/admin/students/" + studentId);
        await expect(adminPage.getByText("Verification history", { exact: true })).toBeVisible();
        await adminPage.getByText("Verification history", { exact: true }).click();
        await expect(adminPage.getByText("Attempt #2", { exact: false })).toBeVisible();
        for (const text of ["Attempt #1", "TAB_SWITCH", "PAGE_HIDDEN", "WINDOW_BLUR", "FULLSCREEN_EXIT", "OFFICIAL_COURSE_OPENED", "LEARNING_COMPLETED", "REJECTED", "NEEDS_RESUBMISSION", "VERIFIED"]) await expect(adminPage.getByText(text, { exact: false }).first()).toBeVisible();
        await adminPage.screenshot({ path: "test-results/student-360.png", fullPage: true });
        const timeline = await db.activityLog.findMany({ where: { studentId }, orderBy: { createdAt: "asc" } });
        const expected = ["LEARNING", "LEARNING_COMPLETED", "ASSESSMENT_AVAILABLE", "ASSESSMENT_FAILED", "REEXAM_REQUIRED", "ASSESSMENT_PASSED", "CERTIFICATE_UNLOCKED", "SUBMITTED", "PENDING_VERIFICATION", "VERIFIED"];
        let offset = 0;
        for (const state of expected) { const i = timeline.findIndex((a, i) => i >= offset && a.action === state); expect(i).toBeGreaterThanOrEqual(offset); offset = i + 1; }
        await adminPage.goto(base + "/admin/assessments?department=" + department.id + "&year=2&section=" + section.id + "&skill=" + skill.id + "&result=pass");
        await expect(adminPage.getByText("1 Attempt Records", { exact: true })).toBeVisible();
        expect(pageErrors).toEqual([]);
        checks("Database dashboard counts, filtered admin assessments, complete Student 360 and ordered lifecycle history");
        await securityChecks(db, adminContext, studentContext, { skillId: skill.id, departmentId: department.id, sectionId: section.id, tag }, checks);
        completed = true;
    } catch (error) {
        const attempts = studentId ? await db.assessmentAttempt.findMany({ where: { studentId }, select: { id: true, startedAt: true, expiresAt: true, submittedAt: true, submissionReason: true, cooldownHours: true, reexamAvailableAt: true, violations: { select: { type: true, occurredAt: true } } } }) : [];
        await writeFile(`test-results/${mode}-failure.json`, JSON.stringify({ tag, message: String(error), attempts }, null, 2));
        await studentPage.screenshot({ path: `test-results/${mode}-failure.png`, fullPage: true }).catch(() => undefined);
        throw error;
    } finally {
        await writeFile(`test-results/${mode}-report.json`, JSON.stringify({ tag, mode, checks: report, pageErrors, completed }, null, 2));
        await closeBrowser();
        // Remove only this run's fixtures; restore settings exactly as they were.
        await db.$transaction(async tx => {
            const users = await tx.user.findMany({ where: { OR: [{ id: admin.id }, { email: tag.toLowerCase() + "@example.test" }] }, select: { id: true } });
            await tx.activityLog.deleteMany({ where: { OR: [{ userId: { in: users.map(u => u.id) } }, ...(studentId ? [{ studentId }] : [])] } });
            await tx.certificateReview.deleteMany({ where: { actorId: { in: users.map(u => u.id) } } });
            if (studentId) await tx.studentProfile.delete({ where: { id: studentId } });
            await tx.user.deleteMany({ where: { id: { in: users.map(u => u.id) } } });
            await tx.question.deleteMany({ where: { skillId: skill.id } });
            await tx.course.delete({ where: { id: course.id } }); await tx.skill.delete({ where: { id: skill.id } });
            await tx.provider.delete({ where: { id: provider.id } }); await tx.skillCategory.delete({ where: { id: category.id } });
            await tx.section.delete({ where: { id: section.id } }); await tx.department.delete({ where: { id: department.id } });
            for (const setting of originalSettings) await tx.adminSetting.upsert({ where: { key: setting.key }, create: { key: setting.key, value: setting.value as Prisma.InputJsonValue }, update: { value: setting.value as Prisma.InputJsonValue } });
            const keys = ["assessmentQuestionCount", "assessmentDurationMinutes", "assessmentViolationLimit", "assessmentCooldownHours", "certificateRequirement", "autoSubmitOnViolation", "passMarksByLevel"];
            await tx.adminSetting.deleteMany({ where: { key: { in: keys.filter(k => !originalSettings.some(s => s.key === k)) } } });
            for (const level of levels) await tx.skillLevel.update({ where: { id: level.id }, data: { passMark: level.passMark } });
        }, { timeout: 30000 });
        await db.$disconnect();
    }
}
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
    runWorkflow().catch(error => { console.error(error); process.exitCode = 1; });
}
