import "dotenv/config";
import { chromium, expect as baseExpect, type Page } from "@playwright/test";
import { PrismaClient, Prisma } from "@prisma/client";
import bcrypt from "bcryptjs";
import { randomUUID } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { securityChecks } from "./e2e-security";
const expect = baseExpect.configure({ timeout: 20000 });

async function main() {
const db = new PrismaClient();
const base = process.env.E2E_BASE_URL || "http://localhost:3000";
const tag = "E2E-" + Date.now();
const password = "Test-" + randomUUID();
const newPassword = "Changed-" + randomUUID();
const report: string[] = [];
const checks = (message: string) => { report.push(message); console.log("PASS " + message); };
const originalSettings = await db.adminSetting.findMany();
const levels = await db.skillLevel.findMany();
if (!levels.length) throw new Error("Configure at least one skill level before testing");
await mkdir("test-results", { recursive: true });
const admin = await db.user.create({ data: { email: tag.toLowerCase() + "-admin@example.test", passwordHash: await bcrypt.hash(password, 12), role: "ADMIN" } });
const department = await db.department.create({ data: { name: tag } });
const section = await db.section.create({ data: { name: "TEST", departmentId: department.id } });
const category = await db.skillCategory.create({ data: { name: tag, slug: tag.toLowerCase() } });
const provider = await db.provider.create({ data: { name: tag, website: "https://developer.mozilla.org" } });
const skill = await db.skill.create({ data: { name: tag + " Skill", slug: tag.toLowerCase(), categoryId: category.id, levelId: levels[0].id } });
const course = await db.course.create({ data: { name: tag + " Official Course", officialUrl: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide", skillId: skill.id, providerId: provider.id, levelId: levels[0].id, certificateAvailable: true } });
await db.question.createMany({ data: Array.from({ length: 5 }, (_, i) => ({ skillId: skill.id, levelId: levels[0].id, type: "SINGLE_CHOICE" as const, difficulty: "EASY" as const, prompt: tag + " test question " + i, options: ["Correct", "Incorrect"], correctAnswer: "Correct" })) });
const browser = await chromium.launch({ channel: "msedge", headless: true });
const adminContext = await browser.newContext({ baseURL: base });
const studentContext = await browser.newContext({ baseURL: base });
const adminPage = await adminContext.newPage();
const studentPage = await studentContext.newPage();
const pageErrors: string[] = [];
for (const page of [adminPage, studentPage]) page.on("pageerror", error => pageErrors.push(error.message));
async function login(page: Page, role: string, identifier: string, secret: string) {
 await page.goto(base + "/" + role + "/login");
 await page.locator('[name="identifier"]').fill(identifier);
 await page.locator('[name="password"]').fill(secret);
 await page.getByRole("button", { name: "Sign in", exact: true }).click();
 await page.waitForURL(/dashboard|password/, { timeout: 30000 });
}
async function jsonPost(path: string, data: object) { return studentContext.request.post(path, { data, maxRedirects: 0 }); }
let studentId = "";
let completed = false;
try {
 await login(adminPage, "admin", admin.email, password); checks("Admin login");
 await adminPage.goto(base + "/admin/settings");
 await adminPage.locator('[name="assessmentQuestionCount"]').fill("2");
 await adminPage.locator('[name="assessmentDurationMinutes"]').fill("3");
 await adminPage.locator('[name="assessmentViolationLimit"]').fill("20");
 await adminPage.locator('[name="assessmentCooldownHours"]').fill("0.005");
 for (const level of levels) await adminPage.locator('[name="passMarks.' + level.name + '"]').fill("1");
 await adminPage.locator('[name="autoSubmitOnViolation"]').check();
 await adminPage.getByRole("button", { name: "Save settings" }).click();
 await adminPage.waitForURL(/saved=1/);
 expect((await db.adminSetting.findUniqueOrThrow({ where: { key: "assessmentQuestionCount" } })).value).toBe(2);
 checks("Admin settings persisted");
 await adminPage.goto(base + "/admin/students");
 const details = { fullName: tag + " Student", registerNumber: tag, email: tag.toLowerCase() + "@example.test", year: "2", temporaryPassword: password };
 for (const [name, value] of Object.entries(details)) await adminPage.locator('[name="' + name + '"]').fill(value);
 await adminPage.locator('[name="departmentId"]').selectOption(department.id);
 await adminPage.locator('[name="sectionId"]').selectOption(section.id);
 await adminPage.getByRole("button", { name: "Create account" }).click();
 await adminPage.waitForURL(/created=1/);
 const student = await db.studentProfile.findUniqueOrThrow({ where: { registerNumber: tag } });
 studentId = student.id;
 checks("Admin creates student");
 await login(studentPage, "student", tag, password);
 expect(studentPage.url()).toContain("/student/password");
 expect((await jsonPost("/api/student/assessment/start", { skillId: skill.id })).status()).toBe(403);
 await studentPage.locator('[name="password"]').fill(newPassword);
 await studentPage.getByRole("button", { name: "Continue to dashboard" }).click();
 await studentPage.waitForURL(/student\/dashboard/);
 checks("Student login and forced password change; API bypass blocked");
 expect((await jsonPost("/api/student/assessment/start", { skillId: skill.id })).status()).toBe(409);
 expect((await jsonPost("/api/student/learning", { skillId: skill.id, action: "complete" })).status()).toBe(409);
 expect((await jsonPost("/api/student/certificates", { skillId: skill.id, credentialId: "UNAUTHORIZED", issuedAt: "2026-01-01" })).status()).toBe(409);
 checks("Learning and certificate prerequisites enforced through API");
 await studentPage.goto(base + "/student/skills/" + skill.slug);
 const popupPromise = studentPage.waitForEvent("popup");
 await studentPage.getByRole("button", { name: "Learn Officially" }).click();
 const official = await popupPromise;
 expect(official.url()).toContain("developer.mozilla.org");
 await official.close();
 await studentPage.goto(base + "/student/skills?q=" + encodeURIComponent(tag));
 await studentPage.getByRole("button", { name: "I Completed Learning" }).click();
 await studentPage.waitForURL(/student\/skills/);
 expect(await db.certificate.count({ where: { studentId } })).toBe(0);
 checks("Official course opens; learning completion does not unlock certificate");
 const start = studentPage.getByRole("button", { name: "Start Assessment" });
 await start.click();
 await studentPage.waitForURL(/student\/assessment\//);
 const attemptId = studentPage.url().split("/").pop()!;
 await studentPage.getByRole("button", { name: "Enter fullscreen and resume" }).click();
 await expect(studentPage.getByRole("button", { name: "Submit assessment" })).toBeVisible();
 const clientId = await studentPage.evaluate(id => sessionStorage.getItem("skillcert_tab_" + id)!, attemptId);
 const first = await db.assessmentAttempt.findUniqueOrThrow({ where: { id: attemptId }, include: { answers: true } });
 expect(await studentPage.evaluate(() => !!document.fullscreenElement)).toBe(true);
 const payload = await (await jsonPost("/api/student/assessment/" + attemptId + "/heartbeat", { clientId })).json();
 expect(JSON.stringify(payload)).not.toMatch(/correctAnswer|explanation|passwordHash|questionSnapshot/);
 expect((await studentContext.request.get("/student/results/" + attemptId, { maxRedirects: 0 })).status()).toBe(307);
 const outsider = await db.question.findFirstOrThrow({ where: { skillId: skill.id, id: { notIn: first.answers.map(a => a.questionId) } } });
 expect((await jsonPost("/api/student/assessment/" + attemptId + "/save", { clientId, responses: { [outsider.id]: "Correct" } })).status()).toBe(400);
 expect((await jsonPost("/api/student/assessment/" + attemptId + "/submit", { clientId, score: 999, passed: true })).status()).toBe(400);
 expect((await jsonPost("/api/student/assessment/" + attemptId + "/claim", { clientId: randomUUID() })).status()).toBe(409);
 const concurrent = await Promise.all([jsonPost("/api/student/assessment/start", { skillId: skill.id }), jsonPost("/api/student/assessment/start", { skillId: skill.id })]);
 expect(concurrent.every(r => r.headers().location?.endsWith(attemptId))).toBe(true);
 expect(await db.assessmentAttempt.count({ where: { studentId, submittedAt: null } })).toBe(1);
 checks("Fullscreen, answer secrecy, result gating, question injection, score tampering and concurrent tab/start defenses");
 await studentPage.getByText("Incorrect", { exact: true }).click();
 await expect(studentPage.getByRole("status")).toContainText("Answer saved");
 const timerBefore = await studentPage.getByRole("timer").textContent();
 await studentPage.reload();
 await studentPage.getByRole("button", { name: "Enter fullscreen and resume" }).click();
 await expect(studentPage.getByRole("button", { name: "Submit assessment" })).toBeVisible();
 const refreshed = await db.assessmentAttempt.findUniqueOrThrow({ where: { id: attemptId } });
 expect(refreshed.expiresAt.getTime()).toBe(first.expiresAt.getTime());
 await expect(studentPage.getByLabel("Incorrect", { exact: true })).toBeChecked();
 expect(await studentPage.getByRole("timer").textContent()).not.toBe("0:00");
 checks("Server timer and saved answers survive refresh (" + timerBefore + ")");
 const devtools = await studentContext.newCDPSession(studentPage);
 await devtools.send("Emulation.setFocusEmulationEnabled", { enabled: false });
 const duplicate = await studentContext.newPage();
 await duplicate.goto(base + "/student/assessment/" + attemptId);
 await expect(duplicate.getByRole("status")).toContainText("already open in another tab");
 await studentPage.bringToFront();
 await duplicate.close();
 await expect.poll(async () => {
  const violations = await db.assessmentViolation.findMany({ where: { attemptId } });
  return ["TAB_SWITCH", "PAGE_HIDDEN", "WINDOW_BLUR"].every(type => violations.some(v => v.type === type));
 }).toBe(true);
 checks("Actual browser tab switch, page hidden and blur logged; duplicate tab blocked");
 if (await studentPage.evaluate(() => !!document.fullscreenElement)) await studentPage.evaluate(() => document.exitFullscreen());
 await expect(studentPage.getByRole("button", { name: "Enter fullscreen and resume" })).toBeVisible();
 await expect.poll(() => db.assessmentViolation.count({ where: { attemptId, type: "FULLSCREEN_EXIT" } })).toBeGreaterThan(0);
 await studentPage.getByRole("button", { name: "Enter fullscreen and resume" }).click();
 await studentPage.getByRole("button", { name: "Submit assessment" }).click();
 await studentPage.waitForURL(/student\/results\//);
 const failed = await db.assessmentAttempt.findUniqueOrThrow({ where: { id: attemptId } });
 expect(failed.passed).toBe(false);
 expect((await jsonPost("/api/student/assessment/start", { skillId: skill.id })).status()).toBe(429);
 const retrySubmit = await jsonPost("/api/student/assessment/" + attemptId + "/submit", { clientId, responses: Object.fromEntries(first.answers.map(a => [a.questionId, "Correct"])) });
 expect(retrySubmit.ok()).toBe(true);
 expect((await db.assessmentAttempt.findUniqueOrThrow({ where: { id: attemptId } })).score).toBe(failed.score);
 checks("Timestamped fullscreen violation, failed result, cooldown and immutable duplicate submission");
 await new Promise(resolve => setTimeout(resolve, Math.max(0, failed.reexamAvailableAt!.getTime() - Date.now()) + 100));
 await studentPage.goto(base + "/student/skills?q=" + encodeURIComponent(tag));
 await studentPage.getByRole("button", { name: "Start Assessment" }).click();
 await studentPage.waitForURL(/student\/assessment\//);
 const secondId = studentPage.url().split("/").pop()!;
 const second = await db.assessmentAttempt.findUniqueOrThrow({ where: { id: secondId }, include: { answers: true } });
 expect(second.attemptNumber).toBe(2);
 expect(second.answers.some(a => !first.answers.some(b => a.questionId === b.questionId))).toBe(true);
 await studentPage.getByRole("button", { name: "Enter fullscreen and resume" }).click();
 await expect(studentPage.getByRole("button", { name: "Submit assessment" })).toBeVisible();
 await studentPage.getByLabel("Correct", { exact: true }).check();
 await expect(studentPage.getByRole("status")).toContainText("Answer saved");
 await studentPage.getByRole("button", { name: "Submit assessment" }).click();
 await studentPage.waitForURL(/student\/results\//);
 expect((await db.assessmentAttempt.findUniqueOrThrow({ where: { id: secondId } })).passed).toBe(true);
 expect((await db.certificate.findUniqueOrThrow({ where: { studentId_skillId: { studentId, skillId: skill.id } } })).status).toBe("UNLOCKED");
 checks("Real cooldown elapses, new randomized re-exam, pass and certificate unlock");
 await studentPage.goto(base + "/student/certificates");
 await studentPage.locator('[name="skillId"]').selectOption(skill.id);
 await studentPage.locator('[name="officialUrl"]').fill("https://example.test/credentials/" + tag);
 await studentPage.locator('[name="credentialId"]').fill(tag + "-CREDENTIAL");
 await studentPage.locator('[name="issuedAt"]').fill("2026-01-01");
 await studentPage.getByRole("button", { name: "Submit certificate" }).click();
 await studentPage.waitForURL(/success=1/);
 const certificate = await db.certificate.findUniqueOrThrow({ where: { studentId_skillId: { studentId, skillId: skill.id } } });
 expect(certificate.status).toBe("PENDING_VERIFICATION");
 await adminPage.goto(base + "/admin/certificates");
 const card = adminPage.locator("article").filter({ hasText: tag + " Student" });
 await card.locator('[name="remarks"]').fill("Please provide the issuer credential identifier.");
 await card.getByRole("button", { name: "Request Resubmission", exact: true }).click();
 await adminPage.waitForURL(/success=1/);
 expect((await db.certificate.findUniqueOrThrow({ where: { id: certificate.id } })).verifiedAt).toBeNull();
 await studentPage.reload();
 await studentPage.locator('[name="credentialId"]').fill(tag + "-ID-ONLY");
 await studentPage.locator('[name="issuedAt"]').fill("2026-01-01");
 await studentPage.getByRole("button", { name: "Submit certificate" }).click();
 await studentPage.waitForURL(/success=1/);
 await adminPage.reload();
 await card.locator('[name="remarks"]').fill("Issuer evidence needs correction.");
 await card.getByRole("button", { name: "Reject", exact: true }).click();
 await adminPage.waitForURL(/success=1/);
 expect((await db.certificate.findUniqueOrThrow({ where: { id: certificate.id } })).status).toBe("REJECTED");
 expect((await jsonPost("/api/student/certificates", { skillId: skill.id, officialUrl: "https://example.test/credentials/" + tag, issuedAt: "2026-01-01" })).status()).toBe(303);
 await adminPage.reload();
 checks("Request resubmission, rejection, ID-only and URL-only submission preserve review history");
 await card.locator('[name="remarks"]').fill("Credential checked against issuer record.");
 await card.getByRole("button", { name: "Approve", exact: true }).click();
 await adminPage.waitForURL(/success=1/);
 await studentPage.reload();
 await expect(studentPage.getByText("VERIFIED", { exact: true })).toBeVisible();
 const verified = await db.studentSkill.findUniqueOrThrow({ where: { studentId_skillId: { studentId, skillId: skill.id } } });
 expect(verified.state).toBe("VERIFIED"); expect(verified.verifiedAt).not.toBeNull();
 await studentPage.screenshot({ path: "test-results/student-verified.png", fullPage: true });
 checks("Certificate submission, admin remarks/approval and immediate student Verified status");
 await studentPage.goto(base + "/student/dashboard");
 for (const label of ["Skills Started", "Learning", "Assessments Attempted", "Passed", "Failed", "Re-exams Pending", "Certificates Submitted", "Certificates Verified", "Certificates Pending"]) await expect(studentPage.getByText(label, { exact: true })).toBeVisible();
 await adminPage.goto(base + "/admin/students/" + studentId);
 await expect(adminPage.getByText("Verification history", { exact: true })).toBeVisible();
 await expect(adminPage.getByText("Attempt #2", { exact: false })).toBeVisible();
 await adminPage.screenshot({ path: "test-results/student-360.png", fullPage: true });
 const timeline = await db.activityLog.findMany({ where: { studentId }, orderBy: { createdAt: "asc" } });
 const expected = ["LEARNING", "LEARNING_COMPLETED", "ASSESSMENT_AVAILABLE", "ASSESSMENT_FAILED", "REEXAM_REQUIRED", "ASSESSMENT_PASSED", "CERTIFICATE_UNLOCKED", "SUBMITTED", "PENDING_VERIFICATION", "VERIFIED"];
 let offset = 0;
 for (const state of expected) { const i = timeline.findIndex((a, i) => i >= offset && a.action === state); expect(i).toBeGreaterThanOrEqual(offset); offset = i + 1; }
 await adminPage.goto(base + "/admin/assessments?department=" + department.id + "&year=2&section=" + section.id + "&skill=" + skill.id + "&result=pass");
 await expect(adminPage.getByText("1 attempts", { exact: true })).toBeVisible();
 expect(pageErrors).toEqual([]);
 checks("Database dashboard counts, filtered admin assessments, complete Student 360 and ordered lifecycle history");
 await securityChecks(db, adminContext, studentContext, { skillId: skill.id, departmentId: department.id, sectionId: section.id, tag }, checks);
 completed = true;
} finally {
 await writeFile("test-results/workflow-report.json", JSON.stringify({ tag, checks: report, pageErrors, completed }, null, 2));
 await browser.close();
 // Remove only this run's fixtures; restore settings exactly as they were.
 await db.$transaction(async tx => {
  const users = await tx.user.findMany({ where: { OR: [{ id: admin.id }, { email: tag.toLowerCase() + "@example.test" }] }, select: { id: true } });
  await tx.activityLog.deleteMany({ where: { OR: [{ userId: { in: users.map(u => u.id) } }, ...(studentId ? [{ studentId }] : [])] } });
  await tx.certificateReview.deleteMany({ where: { actorId: { in: users.map(u => u.id) } } });
  if (studentId) await tx.studentProfile.delete({ where: { id: studentId } });
  await tx.user.deleteMany({ where: { id: { in: users.map(u => u.id) } } });
  await tx.question.deleteMany({ where: { skillId: skill.id } });
  await tx.course.delete({ where: { id: course.id } }); await tx.skill.delete({ where: { id: skill.id } });
  await tx.provider.delete({ where: { id: provider.id } }); await tx.skillCategory.delete({ where: { id: category.id } });
  await tx.section.delete({ where: { id: section.id } }); await tx.department.delete({ where: { id: department.id } });
  for (const setting of originalSettings) await tx.adminSetting.upsert({ where: { key: setting.key }, create: { key: setting.key, value: setting.value as Prisma.InputJsonValue }, update: { value: setting.value as Prisma.InputJsonValue } });
  const keys = ["assessmentQuestionCount", "assessmentDurationMinutes", "assessmentViolationLimit", "assessmentCooldownHours", "certificateRequirement", "autoSubmitOnViolation", "passMarksByLevel"];
  await tx.adminSetting.deleteMany({ where: { key: { in: keys.filter(k => !originalSettings.some(s => s.key === k)) } } });
  for (const level of levels) await tx.skillLevel.update({ where: { id: level.id }, data: { passMark: level.passMark } });
 }, { timeout: 30000 });
 await db.$disconnect();
}
}
main().catch(error => { console.error(error); process.exitCode = 1; });
