import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

interface SkillSeedData {
  category: string;
  categorySlug: string;
  name: string;
  slug: string;
  description: string;
  providerName: string;
  officialUrl?: string;
}

const skillsToSeed: SkillSeedData[] = [
  // 1. Programming & Fundamentals (12 skills)
  {
    category: "Programming",
    categorySlug: "programming",
    name: "C Programming Basics",
    slug: "c-programming-basics",
    description: "Learn foundational syntax, variables, loops, functions, and memory management in C.",
    providerName: "Learning Provider: Open Documentation",
  },
  {
    category: "Programming",
    categorySlug: "programming",
    name: "C++ Fundamentals",
    slug: "cpp-fundamentals",
    description: "Understand object-oriented programming concepts, classes, pointers, and standard template library in C++.",
    providerName: "Learning Provider: Open Documentation",
  },
  {
    category: "Programming",
    categorySlug: "programming",
    name: "Java Foundations",
    slug: "java-foundations",
    description: "Master core Java concepts including OOP principles, collections framework, and basic exception handling.",
    providerName: "Learning Provider: Oracle Docs",
  },
  {
    category: "Programming",
    categorySlug: "programming",
    name: "Python Essentials",
    slug: "python-essentials",
    description: "Build a strong foundation in Python syntax, data structures, functions, modules, and file handling.",
    providerName: "Learning Provider: Python Docs",
  },
  {
    category: "Programming",
    categorySlug: "programming",
    name: "Go Programming Basics",
    slug: "go-programming-basics",
    description: "Introduction to Go programming language, structs, routines, channels, and package management.",
    providerName: "Learning Provider: Go Dev",
  },
  {
    category: "Programming",
    categorySlug: "programming",
    name: "Rust Fundamentals",
    slug: "rust-fundamentals",
    description: "Explore Rust ownership, borrowing, lifetimes, pattern matching, and memory safety without GC.",
    providerName: "Learning Provider: Rust Book",
  },
  {
    category: "Programming",
    categorySlug: "programming",
    name: "C# Essentials",
    slug: "csharp-essentials",
    description: "Learn fundamental C# language features, .NET runtime basics, and object-oriented design.",
    providerName: "Learning Provider: Microsoft Learn",
  },
  {
    category: "Programming",
    categorySlug: "programming",
    name: "TypeScript Essentials",
    slug: "typescript-essentials",
    description: "Understand static typing, interfaces, generics, type inference, and modern TypeScript toolchains.",
    providerName: "Learning Provider: TypeScript Docs",
  },
  {
    category: "Programming",
    categorySlug: "programming",
    name: "Modern JavaScript (ES6+)",
    slug: "modern-javascript-es6",
    description: "Master modern JS features including arrow functions, promises, async/await, modules, and destructuring.",
    providerName: "MDN Web Docs",
    officialUrl: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide",
  },
  {
    category: "Programming",
    categorySlug: "programming",
    name: "Ruby Foundations",
    slug: "ruby-foundations",
    description: "Introduction to Ruby syntax, blocks, object-oriented concepts, and interactive Ruby (IRB).",
    providerName: "Learning Provider: Ruby Lang",
  },
  {
    category: "Programming",
    categorySlug: "programming",
    name: "Swift Basics",
    slug: "swift-basics",
    description: "Understand Swift syntax, optionals, closures, protocols, and iOS development principles.",
    providerName: "Learning Provider: Apple Developer Docs",
  },
  {
    category: "Programming",
    categorySlug: "programming",
    name: "Kotlin Fundamentals",
    slug: "kotlin-fundamentals",
    description: "Learn modern Kotlin syntax, null safety, coroutines, and interoperability with Java.",
    providerName: "Learning Provider: Kotlin Lang",
  },

  // 2. Web Development (12 skills)
  {
    category: "Web Development",
    categorySlug: "web-development",
    name: "HTML5 & Semantic Web",
    slug: "html5-semantic-web",
    description: "Learn semantic markup, forms, accessibility elements, and multimedia in modern HTML5.",
    providerName: "MDN Web Docs",
    officialUrl: "https://developer.mozilla.org/en-US/docs/Learn/HTML",
  },
  {
    category: "Web Development",
    categorySlug: "web-development",
    name: "CSS3 & Flexbox Layouts",
    slug: "css3-flexbox-layouts",
    description: "Master CSS selectors, specificity, box model, Flexbox, and CSS Grid layout systems.",
    providerName: "MDN Web Docs",
    officialUrl: "https://developer.mozilla.org/en-US/docs/Learn/CSS",
  },
  {
    category: "Web Development",
    categorySlug: "web-development",
    name: "Responsive Web Design",
    slug: "responsive-web-design",
    description: "Create mobile-friendly web pages using media queries, fluid grids, and responsive typography.",
    providerName: "Learning Provider: W3C Open Docs",
  },
  {
    category: "Web Development",
    categorySlug: "web-development",
    name: "React Fundamentals",
    slug: "react-fundamentals",
    description: "Understand React components, props, state management, hooks (useState, useEffect), and JSX.",
    providerName: "Learning Provider: React Dev Docs",
  },
  {
    category: "Web Development",
    categorySlug: "web-development",
    name: "Next.js Fundamentals",
    slug: "nextjs-fundamentals",
    description: "Explore App Router, Server Components, Client Components, routing, and data fetching in Next.js.",
    providerName: "Learning Provider: Next.js Docs",
  },
  {
    category: "Web Development",
    categorySlug: "web-development",
    name: "Vue.js Basics",
    slug: "vuejs-basics",
    description: "Learn Vue 3 composition API, directives, reactivity, components, and single-file components (SFC).",
    providerName: "Learning Provider: Vue Docs",
  },
  {
    category: "Web Development",
    categorySlug: "web-development",
    name: "Tailwind CSS Basics",
    slug: "tailwindcss-basics",
    description: "Utility-first CSS styling, custom configuration, responsive variants, and dark mode design.",
    providerName: "Learning Provider: Tailwind Docs",
  },
  {
    category: "Web Development",
    categorySlug: "web-development",
    name: "Web Accessibility (a11y)",
    slug: "web-accessibility-a11y",
    description: "Implement WCAG guidelines, ARIA roles, keyboard navigation, and screen-reader accessibility.",
    providerName: "Learning Provider: W3C WAI",
  },
  {
    category: "Web Development",
    categorySlug: "web-development",
    name: "RESTful API Design Basics",
    slug: "restful-api-design-basics",
    description: "Learn HTTP methods, status codes, JSON payloads, resource naming, and endpoint design.",
    providerName: "Learning Provider: Open API Docs",
  },
  {
    category: "Web Development",
    categorySlug: "web-development",
    name: "GraphQL Fundamentals",
    slug: "graphql-fundamentals",
    description: "Understand queries, mutations, schemas, types, and resolvers in GraphQL APIs.",
    providerName: "Learning Provider: GraphQL Org",
  },
  {
    category: "Web Development",
    categorySlug: "web-development",
    name: "Node.js Core Principles",
    slug: "nodejs-core-principles",
    description: "Learn Node event loop, file system module, HTTP server basics, and NPM package management.",
    providerName: "Learning Provider: Node.js Docs",
  },
  {
    category: "Web Development",
    categorySlug: "web-development",
    name: "Web Performance Optimization",
    slug: "web-performance-optimization",
    description: "Analyze Core Web Vitals, image optimization, bundling, caching strategies, and lazy loading.",
    providerName: "Learning Provider: Web.dev",
  },

  // 3. AI & Generative AI (10 skills)
  {
    category: "Artificial Intelligence",
    categorySlug: "artificial-intelligence",
    name: "AI Concepts & Applications",
    slug: "ai-concepts-applications",
    description: "Fundamental concepts of artificial intelligence, history, terminology, and real-world applications.",
    providerName: "Learning Provider: Open Education",
  },
  {
    category: "Artificial Intelligence",
    categorySlug: "artificial-intelligence",
    name: "Generative AI Foundations",
    slug: "generative-ai-foundations",
    description: "Understand generative models, text and image synthesis, diffusion, and transformer architectures.",
    providerName: "Learning Provider: Open AI Curriculum",
  },
  {
    category: "Artificial Intelligence",
    categorySlug: "artificial-intelligence",
    name: "Prompt Engineering Basics",
    slug: "prompt-engineering-basics",
    description: "Learn zero-shot, few-shot prompting, chain-of-thought, and system prompt optimization.",
    providerName: "Learning Provider: Open AI Curriculum",
  },
  {
    category: "Artificial Intelligence",
    categorySlug: "artificial-intelligence",
    name: "AI Tools for Productivity",
    slug: "ai-tools-productivity",
    description: "Utilize AI writing, coding, summarization, and workflow automation tools effectively.",
    providerName: "Learning Provider: Community Courseware",
  },
  {
    category: "Artificial Intelligence",
    categorySlug: "artificial-intelligence",
    name: "AI Ethics & Responsible AI",
    slug: "ai-ethics-responsible-ai",
    description: "Understand bias, fairness, transparency, privacy, and safety considerations in AI deployment.",
    providerName: "Learning Provider: Open Ethics Guidelines",
  },
  {
    category: "Artificial Intelligence",
    categorySlug: "artificial-intelligence",
    name: "Natural Language Processing Intro",
    slug: "nlp-intro",
    description: "Tokenization, lemmatization, sentiment analysis, embeddings, and text classification basics.",
    providerName: "Learning Provider: Open ML Docs",
  },
  {
    category: "Artificial Intelligence",
    categorySlug: "artificial-intelligence",
    name: "Computer Vision Fundamentals",
    slug: "computer-vision-fundamentals",
    description: "Image processing fundamentals, feature extraction, object detection, and OpenCV basics.",
    providerName: "Learning Provider: OpenCV Docs",
  },
  {
    category: "Artificial Intelligence",
    categorySlug: "artificial-intelligence",
    name: "Copilot & AI Code Assistants",
    slug: "copilot-ai-code-assistants",
    description: "Leverage inline code generation, unit test creation, and AI refactoring techniques.",
    providerName: "Learning Provider: Developer Docs",
  },
  {
    category: "Artificial Intelligence",
    categorySlug: "artificial-intelligence",
    name: "Large Language Models Overview",
    slug: "llm-overview",
    description: "Architecture of LLMs, context windows, tokenization, fine-tuning vs RAG fundamentals.",
    providerName: "Learning Provider: Open AI Curriculum",
  },
  {
    category: "Artificial Intelligence",
    categorySlug: "artificial-intelligence",
    name: "AI Agents & Autonomous Workflows",
    slug: "ai-agents-autonomous-workflows",
    description: "Concepts of agentic loops, tool calling, memory management, and multi-agent coordination.",
    providerName: "Learning Provider: Community Courseware",
  },

  // 4. Machine Learning & Data Science (10 skills)
  {
    category: "Machine Learning",
    categorySlug: "machine-learning",
    name: "Machine Learning Fundamentals",
    slug: "machine-learning-fundamentals",
    description: "Core ML principles, supervised vs unsupervised learning, training/test splits, and metrics.",
    providerName: "Learning Provider: Open ML Docs",
  },
  {
    category: "Machine Learning",
    categorySlug: "machine-learning",
    name: "Python for Data Science",
    slug: "python-for-data-science",
    description: "Using Python for data manipulation, array operations, and scientific computing.",
    providerName: "Learning Provider: Python Data Docs",
  },
  {
    category: "Machine Learning",
    categorySlug: "machine-learning",
    name: "NumPy & Pandas Essentials",
    slug: "numpy-pandas-essentials",
    description: "DataFrames, Series, filtering, grouping, merging, vectorization, and matrix operations.",
    providerName: "Learning Provider: PyData Docs",
  },
  {
    category: "Machine Learning",
    categorySlug: "machine-learning",
    name: "Data Visualization with Matplotlib",
    slug: "data-visualization-matplotlib",
    description: "Creating bar charts, scatter plots, histograms, heatmaps, and customizing chart aesthetics.",
    providerName: "Learning Provider: Matplotlib Docs",
  },
  {
    category: "Machine Learning",
    categorySlug: "machine-learning",
    name: "Scikit-Learn Basics",
    slug: "scikit-learn-basics",
    description: "Building linear regression, logistic regression, decision trees, and evaluating models.",
    providerName: "Learning Provider: Scikit-Learn Docs",
  },
  {
    category: "Machine Learning",
    categorySlug: "machine-learning",
    name: "Feature Engineering Principles",
    slug: "feature-engineering-principles",
    description: "One-hot encoding, feature scaling, missing value imputation, and dimensionality reduction concepts.",
    providerName: "Learning Provider: Open Data Science",
  },
  {
    category: "Machine Learning",
    categorySlug: "machine-learning",
    name: "Supervised Learning Concepts",
    slug: "supervised-learning-concepts",
    description: "Classification and regression algorithms, cost functions, gradient descent, and cross-validation.",
    providerName: "Learning Provider: Open ML Docs",
  },
  {
    category: "Machine Learning",
    categorySlug: "machine-learning",
    name: "Unsupervised Learning Concepts",
    slug: "unsupervised-learning-concepts",
    description: "K-Means clustering, hierarchical clustering, PCA, and anomaly detection basics.",
    providerName: "Learning Provider: Open ML Docs",
  },
  {
    category: "Machine Learning",
    categorySlug: "machine-learning",
    name: "Jupyter Notebooks Guide",
    slug: "jupyter-notebooks-guide",
    description: "Interactive data exploration, markdown documentation, kernel execution, and reproducible research.",
    providerName: "Learning Provider: Jupyter Org",
  },
  {
    category: "Machine Learning",
    categorySlug: "machine-learning",
    name: "Statistical Methods for Data Science",
    slug: "statistical-methods-data-science",
    description: "Mean, variance, standard deviation, probability distributions, hypothesis testing, and p-values.",
    providerName: "Learning Provider: Open Statistics",
  },

  // 5. Data Analytics & SQL (10 skills)
  {
    category: "Data Analytics",
    categorySlug: "data-analytics",
    name: "SQL Querying Fundamentals",
    slug: "sql-querying-fundamentals",
    description: "SELECT queries, WHERE filtering, ORDER BY, GROUP BY, HAVING, and aggregate functions.",
    providerName: "Learning Provider: Open Database Docs",
  },
  {
    category: "Data Analytics",
    categorySlug: "data-analytics",
    name: "Relational Database Concepts",
    slug: "relational-database-concepts",
    description: "Tables, primary keys, foreign keys, relationships, normalization (1NF, 2NF, 3NF), and ER diagrams.",
    providerName: "Learning Provider: Open Database Docs",
  },
  {
    category: "Data Analytics",
    categorySlug: "data-analytics",
    name: "PostgreSQL Essentials",
    slug: "postgresql-essentials",
    description: "Data types, indexes, transactions, joins, subqueries, and views in PostgreSQL.",
    providerName: "Learning Provider: PostgreSQL Docs",
  },
  {
    category: "Data Analytics",
    categorySlug: "data-analytics",
    name: "MySQL Basics",
    slug: "mysql-basics",
    description: "Database administration basics, DDL, DML, user permissions, and basic index optimization.",
    providerName: "Learning Provider: MySQL Docs",
  },
  {
    category: "Data Analytics",
    categorySlug: "data-analytics",
    name: "Microsoft Excel Data Analysis",
    slug: "excel-data-analysis",
    description: "Data cleaning, Pivot Tables, conditional formatting, data validation, and basic charting.",
    providerName: "Learning Provider: Microsoft Learn",
  },
  {
    category: "Data Analytics",
    categorySlug: "data-analytics",
    name: "Excel Formulas & Functions",
    slug: "excel-formulas-functions",
    description: "VLOOKUP, XLOOKUP, INDEX/MATCH, SUMIFS, COUNTIFS, and logical IF statements.",
    providerName: "Learning Provider: Microsoft Learn",
  },
  {
    category: "Data Analytics",
    categorySlug: "data-analytics",
    name: "Power BI Dashboarding Fundamentals",
    slug: "power-bi-dashboarding-fundamentals",
    description: "Importing data, Power Query transformations, DAX measure basics, and interactive visuals.",
    providerName: "Learning Provider: Microsoft Learn",
  },
  {
    category: "Data Analytics",
    categorySlug: "data-analytics",
    name: "Tableau Data Visualization",
    slug: "tableau-data-visualization",
    description: "Connecting data sources, dimensions vs measures, creating dashboards, and story points.",
    providerName: "Learning Provider: Tableau Training",
  },
  {
    category: "Data Analytics",
    categorySlug: "data-analytics",
    name: "Data Wrangling & Cleaning",
    slug: "data-wrangling-cleaning",
    description: "Identifying duplicates, handling missing data, string parsing, and date time conversions.",
    providerName: "Learning Provider: Open Analytics",
  },
  {
    category: "Data Analytics",
    categorySlug: "data-analytics",
    name: "Business Intelligence Overview",
    slug: "business-intelligence-overview",
    description: "BI architecture, ETL pipelines, data warehousing concepts, and KPI metrics design.",
    providerName: "Learning Provider: Open Analytics",
  },

  // 6. Cloud Computing (10 skills)
  {
    category: "Cloud Computing",
    categorySlug: "cloud-computing",
    name: "Cloud Computing Fundamentals",
    slug: "cloud-computing-fundamentals",
    description: "IaaS, PaaS, SaaS models, cloud security basics, scalability, and cost management.",
    providerName: "Learning Provider: Open Cloud Curriculum",
  },
  {
    category: "Cloud Computing",
    categorySlug: "cloud-computing",
    name: "AWS Cloud Practitioner Basics",
    slug: "aws-cloud-practitioner-basics",
    description: "EC2, S3, IAM, VPC, RDS, and AWS Global Infrastructure overview.",
    providerName: "Learning Provider: AWS Skill Builder",
  },
  {
    category: "Cloud Computing",
    categorySlug: "cloud-computing",
    name: "Azure Fundamentals Concepts",
    slug: "azure-fundamentals-concepts",
    description: "Azure Virtual Machines, App Services, Blob Storage, Azure AD, and Resource Groups.",
    providerName: "Learning Provider: Microsoft Learn",
  },
  {
    category: "Cloud Computing",
    categorySlug: "cloud-computing",
    name: "Google Cloud Platform Essentials",
    slug: "gcp-essentials",
    description: "Compute Engine, Cloud Storage, BigQuery, and GCP console management.",
    providerName: "Learning Provider: Google Cloud Skills",
  },
  {
    category: "Cloud Computing",
    categorySlug: "cloud-computing",
    name: "Serverless Computing Overview",
    slug: "serverless-computing-overview",
    description: "Event-driven architecture, AWS Lambda, Azure Functions, and cold start considerations.",
    providerName: "Learning Provider: Open Cloud Curriculum",
  },
  {
    category: "Cloud Computing",
    categorySlug: "cloud-computing",
    name: "Microservices Architecture Basics",
    slug: "microservices-architecture-basics",
    description: "Monolith vs microservices, service boundaries, API gateways, and distributed logging.",
    providerName: "Learning Provider: Open Architecture",
  },
  {
    category: "Cloud Computing",
    categorySlug: "cloud-computing",
    name: "Virtualization & Containers Intro",
    slug: "virtualization-containers-intro",
    description: "Hypervisors, virtual machines vs containerized runtimes, and resource isolation.",
    providerName: "Learning Provider: Open Tech Docs",
  },
  {
    category: "Cloud Computing",
    categorySlug: "cloud-computing",
    name: "Cloud Storage Solutions",
    slug: "cloud-storage-solutions",
    description: "Block storage, object storage, file storage, lifecycle rules, and bucket policies.",
    providerName: "Learning Provider: Open Cloud Curriculum",
  },
  {
    category: "Cloud Computing",
    categorySlug: "cloud-computing",
    name: "Cloud IAM & Access Control",
    slug: "cloud-iam-access-control",
    description: "Principle of least privilege, role-based access control (RBAC), policies, and MFA.",
    providerName: "Learning Provider: Open Cloud Curriculum",
  },
  {
    category: "Cloud Computing",
    categorySlug: "cloud-computing",
    name: "Cloud Cost Optimization",
    slug: "cloud-cost-optimization",
    description: "Reserved instances, spot pricing, auto-scaling, tagging policies, and budget alerts.",
    providerName: "Learning Provider: Open Cloud Curriculum",
  },

  // 7. DevOps & Linux (10 skills)
  {
    category: "DevOps & Linux",
    categorySlug: "devops-linux",
    name: "Linux Command Line Fundamentals",
    slug: "linux-command-line-fundamentals",
    description: "File system navigation (cd, ls, pwd), file permissions (chmod, chown), grep, find, and piping.",
    providerName: "Learning Provider: Linux Foundation Open",
  },
  {
    category: "DevOps & Linux",
    categorySlug: "devops-linux",
    name: "Bash Shell Scripting",
    slug: "bash-shell-scripting",
    description: "Variables, conditionals, loops, functions, environment variables, and automated shell scripts.",
    providerName: "Learning Provider: Open Linux Guide",
  },
  {
    category: "DevOps & Linux",
    categorySlug: "devops-linux",
    name: "Git Version Control Basics",
    slug: "git-version-control-basics",
    description: "git init, commit, push, pull, branch, merge, diff, status, and resolving merge conflicts.",
    providerName: "Learning Provider: Git Open Docs",
  },
  {
    category: "DevOps & Linux",
    categorySlug: "devops-linux",
    name: "GitHub Workflow & Collaboration",
    slug: "github-workflow-collaboration",
    description: "Repositories, Pull Requests, Code Reviews, Issues, Forking, and GitHub Actions intro.",
    providerName: "Learning Provider: GitHub Docs",
  },
  {
    category: "DevOps & Linux",
    categorySlug: "devops-linux",
    name: "Docker Containerization Essentials",
    slug: "docker-containerization-essentials",
    description: "Dockerfiles, images, containers, volumes, networking, and docker-compose basics.",
    providerName: "Learning Provider: Docker Docs",
  },
  {
    category: "DevOps & Linux",
    categorySlug: "devops-linux",
    name: "CI/CD Pipeline Fundamentals",
    slug: "cicd-pipeline-fundamentals",
    description: "Automated build, test, and deployment concepts, triggers, artifacts, and pipelines.",
    providerName: "Learning Provider: Open DevOps Curriculum",
  },
  {
    category: "DevOps & Linux",
    categorySlug: "devops-linux",
    name: "Kubernetes Core Concepts",
    slug: "kubernetes-core-concepts",
    description: "Pods, Deployments, Services, ConfigMaps, Secrets, and kubectl command basics.",
    providerName: "Learning Provider: Kubernetes Docs",
  },
  {
    category: "DevOps & Linux",
    categorySlug: "devops-linux",
    name: "YAML & Configuration Syntax",
    slug: "yaml-configuration-syntax",
    description: "Key-value pairs, lists, indentation rules, scalars, and validating YAML specs.",
    providerName: "Learning Provider: Open DevOps Docs",
  },
  {
    category: "DevOps & Linux",
    categorySlug: "devops-linux",
    name: "Infrastructure as Code Intro",
    slug: "infrastructure-as-code-intro",
    description: "Declarative infrastructure, Terraform basics, state files, providers, and resources.",
    providerName: "Learning Provider: Open Infrastructure Docs",
  },
  {
    category: "DevOps & Linux",
    categorySlug: "devops-linux",
    name: "System Monitoring & Logging",
    slug: "system-monitoring-logging",
    description: "Log aggregation, metrics collection, CPU/Memory monitoring, and alert thresholds.",
    providerName: "Learning Provider: Open DevOps Docs",
  },

  // 8. Cybersecurity & Networking (10 skills)
  {
    category: "Cybersecurity",
    categorySlug: "cybersecurity",
    name: "Cybersecurity Fundamentals",
    slug: "cybersecurity-fundamentals",
    description: "CIA Triad (Confidentiality, Integrity, Availability), threat actors, attack vectors, and defenses.",
    providerName: "Learning Provider: Open Security Docs",
  },
  {
    category: "Cybersecurity",
    categorySlug: "cybersecurity",
    name: "Network Protocol Essentials",
    slug: "network-protocol-essentials",
    description: "OSI Model, TCP/IP, IPv4/IPv6, DNS, DHCP, HTTP/HTTPS, and Wireshark basics.",
    providerName: "Learning Provider: Open Networking Guide",
  },
  {
    category: "Cybersecurity",
    categorySlug: "cybersecurity",
    name: "Web Application Security (OWASP)",
    slug: "web-app-security-owasp",
    description: "OWASP Top 10 vulnerabilities: SQL injection, XSS, CSRF, broken authentication, and mitigation.",
    providerName: "Learning Provider: OWASP Open Docs",
  },
  {
    category: "Cybersecurity",
    categorySlug: "cybersecurity",
    name: "Cryptography & Hashing Basics",
    slug: "cryptography-hashing-basics",
    description: "Symmetric vs asymmetric encryption, RSA, AES, SHA-256 hashing, and digital signatures.",
    providerName: "Learning Provider: Open Security Docs",
  },
  {
    category: "Cybersecurity",
    categorySlug: "cybersecurity",
    name: "Information Security Policies",
    slug: "information-security-policies",
    description: "Security awareness, password management, data classification, and incident response basics.",
    providerName: "Learning Provider: Open Security Docs",
  },
  {
    category: "Cybersecurity",
    categorySlug: "cybersecurity",
    name: "Firewall & Network Defense",
    slug: "firewall-network-defense",
    description: "Packet filtering, stateful firewalls, IDS/IPS concepts, and network segmentation.",
    providerName: "Learning Provider: Open Security Docs",
  },
  {
    category: "Cybersecurity",
    categorySlug: "cybersecurity",
    name: "Ethical Hacking Intro",
    slug: "ethical-hacking-intro",
    description: "Reconnaissance, scanning, vulnerability assessment, exploitation basics, and ethical guidelines.",
    providerName: "Learning Provider: Open Security Docs",
  },
  {
    category: "Cybersecurity",
    categorySlug: "cybersecurity",
    name: "Wireless Network Security",
    slug: "wireless-network-security",
    description: "WPA2/WPA3 protocols, SSID broadcasting, rogue access points, and wireless encryption.",
    providerName: "Learning Provider: Open Security Docs",
  },
  {
    category: "Cybersecurity",
    categorySlug: "cybersecurity",
    name: "Endpoint Protection Essentials",
    slug: "endpoint-protection-essentials",
    description: "Antivirus, EDR basics, patch management, device encryption, and privilege escalation prevention.",
    providerName: "Learning Provider: Open Security Docs",
  },
  {
    category: "Cybersecurity",
    categorySlug: "cybersecurity",
    name: "Cloud Security Principles",
    slug: "cloud-security-principles",
    description: "Shared responsibility model, cloud compliance, data encryption at rest and in transit.",
    providerName: "Learning Provider: Open Security Docs",
  },

  // 9. UI/UX & Product Design (8 skills)
  {
    category: "UI/UX Design",
    categorySlug: "ui-ux-design",
    name: "UI/UX Design Fundamentals",
    slug: "ui-ux-design-fundamentals",
    description: "User-centered design principles, visual hierarchy, typography, color theory, and usability.",
    providerName: "Learning Provider: Open Design Curriculum",
  },
  {
    category: "UI/UX Design",
    categorySlug: "ui-ux-design",
    name: "Figma Interface Design Basics",
    slug: "figma-interface-design-basics",
    description: "Frames, components, auto-layout, constraints, variants, and vector editing in Figma.",
    providerName: "Learning Provider: Open Design Curriculum",
  },
  {
    category: "UI/UX Design",
    categorySlug: "ui-ux-design",
    name: "User Research & Personas",
    slug: "user-research-personas",
    description: "Conducting user interviews, creating user personas, journey mapping, and empathy maps.",
    providerName: "Learning Provider: Open Design Curriculum",
  },
  {
    category: "UI/UX Design",
    categorySlug: "ui-ux-design",
    name: "Wireframing & Prototyping",
    slug: "wireframing-prototyping",
    description: "Low-fidelity wireframes, interactive prototyping, micro-interactions, and usability testing.",
    providerName: "Learning Provider: Open Design Curriculum",
  },
  {
    category: "UI/UX Design",
    categorySlug: "ui-ux-design",
    name: "Design Systems Concepts",
    slug: "design-systems-concepts",
    description: "Design tokens, component libraries, style guides, accessibility tokens, and team handoff.",
    providerName: "Learning Provider: Open Design Curriculum",
  },
  {
    category: "UI/UX Design",
    categorySlug: "ui-ux-design",
    name: "Mobile Interface Design",
    slug: "mobile-interface-design",
    description: "Touch targets, iOS Human Interface Guidelines, Android Material Design, and gesture patterns.",
    providerName: "Learning Provider: Open Design Curriculum",
  },
  {
    category: "UI/UX Design",
    categorySlug: "ui-ux-design",
    name: "Information Architecture",
    slug: "information-architecture",
    description: "Site maps, card sorting, navigation patterns, search design, and content hierarchy.",
    providerName: "Learning Provider: Open Design Curriculum",
  },
  {
    category: "UI/UX Design",
    categorySlug: "ui-ux-design",
    name: "Design Handoff & Developer Specs",
    slug: "design-handoff-developer-specs",
    description: "Exporting assets, spec inspection, redlining, responsive breakpoints, and token naming.",
    providerName: "Learning Provider: Open Design Curriculum",
  },

  // 10. Automation & Scripting (8 skills)
  {
    category: "Automation",
    categorySlug: "automation",
    name: "Python Automation & Scripting",
    slug: "python-automation-scripting",
    description: "Automating repetitive file tasks, web scraping (BeautifulSoup), and OS interaction.",
    providerName: "Learning Provider: Python Docs",
  },
  {
    category: "Automation",
    categorySlug: "automation",
    name: "Robotic Process Automation Intro",
    slug: "rpa-intro",
    description: "RPA fundamentals, workflow bots, data extraction, and business process automation.",
    providerName: "Learning Provider: Open Automation Docs",
  },
  {
    category: "Automation",
    categorySlug: "automation",
    name: "No-Code Workflow Automation",
    slug: "no-code-workflow-automation",
    description: "Connecting APIs, triggers, actions, webhooks, and automated notifications using no-code platforms.",
    providerName: "Learning Provider: Open Automation Docs",
  },
  {
    category: "Automation",
    categorySlug: "automation",
    name: "Task Scheduling & Cron Jobs",
    slug: "task-scheduling-cron-jobs",
    description: "Cron syntax, scheduled background jobs, log redirection, and automated maintenance.",
    providerName: "Learning Provider: Open Linux Guide",
  },
  {
    category: "Automation",
    categorySlug: "automation",
    name: "Web Scraping & Data Extraction",
    slug: "web-scraping-data-extraction",
    description: "HTML parsing, handling rate limits, proxies, robots.txt compliance, and structured JSON output.",
    providerName: "Learning Provider: Open Python Docs",
  },
  {
    category: "Automation",
    categorySlug: "automation",
    name: "API Integration & Webhooks",
    slug: "api-integration-webhooks",
    description: "Consuming REST APIs, bearer tokens, error handling, rate limiting, and webhook listeners.",
    providerName: "Learning Provider: Open API Docs",
  },
  {
    category: "Automation",
    categorySlug: "automation",
    name: "Automated Email & Reporting",
    slug: "automated-email-reporting",
    description: "Generating PDF reports programmatically, SMTP integration, and scheduled email alerts.",
    providerName: "Learning Provider: Open Tech Docs",
  },
  {
    category: "Automation",
    categorySlug: "automation",
    name: "Browser Automation with Playwright",
    slug: "browser-automation-playwright",
    description: "Automating browser navigation, form fills, screenshots, and E2E testing scripts.",
    providerName: "Learning Provider: Playwright Open Docs",
  },

  // 11. Communication & Career Skills (10 skills)
  {
    category: "Career & Soft Skills",
    categorySlug: "career-soft-skills",
    name: "Technical Writing Fundamentals",
    slug: "technical-writing-fundamentals",
    description: "Writing clear API documentation, READMEs, architectural decision records, and technical specs.",
    providerName: "Learning Provider: Open Docs Community",
  },
  {
    category: "Career & Soft Skills",
    categorySlug: "career-soft-skills",
    name: "Agile & Scrum Methodology",
    slug: "agile-scrum-methodology",
    description: "Scrum roles (Product Owner, Scrum Master), sprints, backlog grooming, standups, and retrospectives.",
    providerName: "Learning Provider: Open Agile Guide",
  },
  {
    category: "Career & Soft Skills",
    categorySlug: "career-soft-skills",
    name: "Effective Team Communication",
    slug: "effective-team-communication",
    description: "Active listening, constructive feedback, technical presentations, and cross-functional alignment.",
    providerName: "Learning Provider: Open Career Skills",
  },
  {
    category: "Career & Soft Skills",
    categorySlug: "career-soft-skills",
    name: "Problem-Solving for Engineers",
    slug: "problem-solving-for-engineers",
    description: "Deconstructing complex bugs, root cause analysis (5 Whys), debugging strategies, and logic.",
    providerName: "Learning Provider: Open Career Skills",
  },
  {
    category: "Career & Soft Skills",
    categorySlug: "career-soft-skills",
    name: "Technical Interview Preparation",
    slug: "technical-interview-prep",
    description: "Data structure review, algorithmic problem solving, mock technical interviews, and system design basics.",
    providerName: "Learning Provider: Open Career Skills",
  },
  {
    category: "Career & Soft Skills",
    categorySlug: "career-soft-skills",
    name: "Git PR & Code Review Practices",
    slug: "git-pr-code-review-practices",
    description: "Writing informative pull request descriptions, atomic commits, reviewing code constructively, and CI checks.",
    providerName: "Learning Provider: GitHub Open Docs",
  },
  {
    category: "Career & Soft Skills",
    categorySlug: "career-soft-skills",
    name: "Remote Work & Async Communication",
    slug: "remote-work-async-communication",
    description: "Asynchronous communication workflows, documentation-first culture, and time management.",
    providerName: "Learning Provider: Open Career Skills",
  },
  {
    category: "Career & Soft Skills",
    categorySlug: "career-soft-skills",
    name: "Productivity & Time Management",
    slug: "productivity-time-management",
    description: "Time blocking, Pomodoro technique, task prioritization (Eisenhower Matrix), and deep work.",
    providerName: "Learning Provider: Open Career Skills",
  },
  {
    category: "Career & Soft Skills",
    categorySlug: "career-soft-skills",
    name: "Project Management Essentials",
    slug: "project-management-essentials",
    description: "Project scope definition, Gantt charts, risk mitigation, milestone tracking, and stakeholder communication.",
    providerName: "Learning Provider: Open Management Guide",
  },
  {
    category: "Career & Soft Skills",
    categorySlug: "career-soft-skills",
    name: "Open Source Contribution Basics",
    slug: "open-source-contribution-basics",
    description: "Finding beginner-friendly issues, understanding licenses (MIT, Apache), code of conduct, and submitting PRs.",
    providerName: "Learning Provider: Open Source Guide",
  },

  // 12. Developer Tools & Productivity (10 skills)
  {
    category: "Developer Tools",
    categorySlug: "developer-tools",
    name: "VS Code Power User Guide",
    slug: "vscode-power-user-guide",
    description: "Keyboard shortcuts, essential extensions, multi-root workspaces, debugging, and task configuration.",
    providerName: "Learning Provider: VS Code Docs",
  },
  {
    category: "Developer Tools",
    categorySlug: "developer-tools",
    name: "Command Line Productivity",
    slug: "command-line-productivity",
    description: "Custom aliases, zsh/oh-my-zsh, tmux terminal multiplexer, fzf fuzzy search, and CLI tools.",
    providerName: "Learning Provider: Open CLI Guide",
  },
  {
    category: "Developer Tools",
    categorySlug: "developer-tools",
    name: "Markdown & Technical Documentation",
    slug: "markdown-technical-docs",
    description: "GitHub Flavored Markdown syntax, tables, mermaid diagrams, code blocks, and static site generators.",
    providerName: "Learning Provider: Open Docs Guide",
  },
  {
    category: "Developer Tools",
    categorySlug: "developer-tools",
    name: "Postman API Testing Basics",
    slug: "postman-api-testing-basics",
    description: "Creating request collections, environment variables, automated assertion tests, and mock servers.",
    providerName: "Learning Provider: Postman Docs",
  },
  {
    category: "Developer Tools",
    categorySlug: "developer-tools",
    name: "Chrome DevTools Essentials",
    slug: "chrome-devtools-essentials",
    description: "DOM inspection, network tab analysis, console debugging, performance profiling, and lighthouse.",
    providerName: "Learning Provider: Chrome Dev Docs",
  },
  {
    category: "Developer Tools",
    categorySlug: "developer-tools",
    name: "RegEx (Regular Expressions) Basics",
    slug: "regex-basics",
    description: "Pattern matching, character classes, quantifiers, anchors, capture groups, and testing regular expressions.",
    providerName: "Learning Provider: Open RegEx Guide",
  },
  {
    category: "Developer Tools",
    categorySlug: "developer-tools",
    name: "Environment Variables & Configuration",
    slug: "environment-variables-config",
    description: ".env files, secret management, 12-factor app principles, and environment-specific configs.",
    providerName: "Learning Provider: Open Tech Docs",
  },
  {
    category: "Developer Tools",
    categorySlug: "developer-tools",
    name: "Package Managers (NPM / Yarn / PNPM)",
    slug: "package-managers-npm-yarn-pnpm",
    description: "package.json, lockfiles, semantic versioning (^ vs ~), dependency resolution, and custom npm scripts.",
    providerName: "Learning Provider: NPM Docs",
  },
  {
    category: "Developer Tools",
    categorySlug: "developer-tools",
    name: "Linters & Code Formatter (ESLint / Prettier)",
    slug: "linters-formatters-eslint-prettier",
    description: "Configuring lint rules, auto-fix on save, husky pre-commit hooks, and code style consistency.",
    providerName: "Learning Provider: Open Tooling Docs",
  },
  {
    category: "Developer Tools",
    categorySlug: "developer-tools",
    name: "Build Tools (Vite / Webpack Intro)",
    slug: "build-tools-vite-webpack",
    description: "Module bundling, hot module replacement (HMR), tree shaking, assets loading, and production builds.",
    providerName: "Learning Provider: Vite Docs",
  },
];

async function seedBeginnerSkills() {
  console.log("Starting seeding of 100+ Beginner skills...");

  const beginnerLevel = await db.skillLevel.upsert({
    where: { name: "Beginner" },
    update: { order: 1, passMark: 30 },
    create: { name: "Beginner", order: 1, passMark: 30 },
  });

  let seededCount = 0;

  // 1. Bulk insert Categories
  const uniqueCategories = Array.from(new Set(skillsToSeed.map(s => JSON.stringify({ name: s.category, slug: s.categorySlug })))).map(s => JSON.parse(s));
  await db.skillCategory.createMany({
    data: uniqueCategories.map(c => ({ name: c.name, slug: c.slug, active: true })),
    skipDuplicates: true,
  });
  const categories = await db.skillCategory.findMany({ select: { id: true, slug: true } });
  const categoryMap = new Map(categories.map(c => [c.slug, c.id]));

  // 2. Bulk insert Providers
  const uniqueProviders = Array.from(new Set(skillsToSeed.map(s => JSON.stringify({ name: s.providerName, url: s.officialUrl || null })))).map(s => JSON.parse(s));
  await db.provider.createMany({
    data: uniqueProviders.map(p => ({ name: p.name, website: p.url, description: `Verified course resources from ${p.name}`, active: true })),
    skipDuplicates: true,
  });
  const providers = await db.provider.findMany({ select: { id: true, name: true } });
  const providerMap = new Map(providers.map(p => [p.name, p.id]));

  // 3. Bulk insert Skills
  await db.skill.createMany({
    data: skillsToSeed.map(item => ({
      name: item.name,
      slug: item.slug,
      description: item.description,
      categoryId: categoryMap.get(item.categorySlug)!,
      levelId: beginnerLevel.id,
      active: true,
    })),
    skipDuplicates: true,
  });

  const skills = await db.skill.findMany({
    where: { levelId: beginnerLevel.id },
    select: { id: true, slug: true },
  });
  const skillMap = new Map(skills.map(s => [s.slug, s.id]));

  // 4. Bulk insert Courses
  await db.course.createMany({
    data: skillsToSeed.map(item => ({
      name: `${item.name} Official Course`,
      skillId: skillMap.get(item.slug)!,
      providerId: providerMap.get(item.providerName)!,
      levelId: beginnerLevel.id,
      officialUrl: item.officialUrl || "OFFICIAL_LINK_PENDING",
      isFree: true,
      certificateAvailable: true,
      description: item.description,
      durationMinutes: 60,
      active: true,
    })),
    skipDuplicates: true,
  });

  const totalBeginnerSkills = skills.length;
  console.log(`Successfully seeded ${skillsToSeed.length} skills! Total Beginner skills in database: ${totalBeginnerSkills}`);
}

seedBeginnerSkills()
  .catch((e) => {
    console.error("Error seeding beginner skills:", e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
